{% set name = "pyscicat" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SciCatProject/pyscicat/archive/v{{ version }}.tar.gz
  sha256: 7776e275e82c4535aa58986a0e996f0924778e0e15015880149ac312b15fb71b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - pydantic
    - python >=3.7
    - requests

test:
  imports:
    - pyscicat
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scicatproject/pyscicat
  summary: Code for communicating to a SciCat backend server python
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://scicatproject.github.io/pyscicat/

extra:
  recipe-maintainers:
    - abigailalexander
    - RFIMarvin
